# Generated by Django 4.2.4 on 2023-09-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmenttitle', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('food', 'Food'), ('travel', 'Travel')], max_length=10, null=True)),
                ('approveddate', models.DateTimeField(blank=True)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.employee')),
            ],
        ),
    ]
